name: demo_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.1.0
  dio: 5.3.2
  firebase_core: ^2.16.0
  flutter_local_notifications: ^15.1.0+1
  shared_preferences: ^2.2.0
  firebase_messaging: ^14.6.6
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.10.0
  get_storage: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "assets/images/labit.png"
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/images/labit.png"

flutter:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

  uses-material-design: true
