// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtDSypY8unFo13grNmeZd4WGfHm9wAwWQ',
    appId: '1:505626434408:web:05f7f5aa6a2d9e97dc14dd',
    messagingSenderId: '505626434408',
    projectId: 'picvie-mobile',
    authDomain: 'picvie-mobile.firebaseapp.com',
    storageBucket: 'picvie-mobile.appspot.com',
    measurementId: 'G-3FVEBEVGTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC81mCTBbUDMwL6nMXxi9BUBKe1thKFQII',
    appId: '1:505626434408:android:aa8945a3c633ba2cdc14dd',
    messagingSenderId: '505626434408',
    projectId: 'picvie-mobile',
    storageBucket: 'picvie-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWjamSbNa00ytgT3MuA7WulJq6_jncvIc',
    appId: '1:505626434408:ios:aed5a876522eac76dc14dd',
    messagingSenderId: '505626434408',
    projectId: 'picvie-mobile',
    storageBucket: 'picvie-mobile.appspot.com',
    iosClientId: '505626434408-djgc11gbfacifcok15kfsr5407pv6juf.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWjamSbNa00ytgT3MuA7WulJq6_jncvIc',
    appId: '1:505626434408:ios:4a7cb8787411490fdc14dd',
    messagingSenderId: '505626434408',
    projectId: 'picvie-mobile',
    storageBucket: 'picvie-mobile.appspot.com',
    iosClientId: '505626434408-oormjjs2g64b7lao74ekokj00bdorn8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoMobile.RunnerTests',
  );
}
